version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: secure_random_username
      POSTGRES_PASSWORD: secure_random_password
      POSTGRES_DB: chat
    ports:
      - "3001:5432"
    expose:
      - "5432"
    restart: always

  nsqlookupd:
    image: nsqio/nsq
    container_name: nsqlookupd
    command: /nsqlookupd
    ports:
      - "3002:4160"
    expose:
      - "4160"

  nsqd:
    image: nsqio/nsq
    container_name: nsqd
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    ports:
      - "3003:4150"
    expose:
      - "4150"

  nsqadmin:
    image: nsqio/nsq
    container_name: nsqadmin
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    ports:
      - "3004:4171"
    expose:
      - "4171"

  golang-migrate:
    image: migrate/migrate
    container_name: golang-migrate
    command: ["-path", "/migrations", "-database", "postgres://secure_random_username:secure_random_password@postgres/chat?sslmode=disable", "up"]
    volumes:
      - ./migrations:/migrations
    depends_on:
      - postgres

  golang-app:
    image: golang:latest
    container_name: golang-app
    volumes:
      - ./:/ws-chat
    working_dir: /ws-chat
    ports:
      - "8080:8080"
    command: bash -c "go mod tidy && go run cmd/app/main.go"